# Generated by Django 4.2.1 on 2023-05-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('opis', models.CharField(default='Dodaj opis :D', max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('photo', models.ImageField(upload_to='')),
                ('wkoszyku', models.BooleanField(default=False)),
                ('licznik', models.DecimalField(decimal_places=0, default=1, max_digits=5)),
            ],
        ),
    ]
