# Generated by Django 4.2.2 on 2023-06-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
