export const dataProducts = [
    {
        id : 1,
        img : "img/car1.jpg",
        title : "Car1",
        price : 12,
        company : "eeeeeee",
        info : "rrrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrr rrrrrrrrrrrrrr rrrrrrrrrr",
        inCart : false,
        count : 1, 
    },
    {
        id : 2,
        img : "img/car2.jpg",
        title : "Car2",
        price : 34,
        company : "sssss",
        info : "dddddd dddddddddddddd ddddddddddd",
        inCart : false,
        count : 1, 
    },
    {
        id : 3,
        img : "img/car3.jpg",
        title : "Car3",
        price : 56,
        company : "xxxxxx ",
        info : "cccccccc ccccccccccccc cccccccccccc ccccccccccc ccccc",
        inCart : false,
        count : 1, 
    },
    {
        id : 4,
        img : "img/car1.jpg",
        title : "Car4",
        price : 12,
        company : "eeeeeee",
        info : "rrrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrr rrrrrrrrrrrrrr rrrrrrrrrr",
        inCart : false,
        count : 1, 
    },
    {
        id : 5,
        img : "img/car2.jpg",
        title : "Car5",
        price : 34,
        company : "sssss",
        info : "dddddd dddddddddddddd ddddddddddd",
        inCart : false,
        count : 1, 
    },
    {
        id : 6,
        img : "img/car3.jpg",
        title : "Car6",
        price : 56,
        company : "xxxxxx ",
        info : "cccccccc ccccccccccccc cccccccccccc ccccccccccc ccccc",
        inCart : false,
        count : 1, 
    },
    {
        id : 7,
        img : "img/car1.jpg",
        title : "Car7",
        price : 12,
        company : "eeeeeee",
        info : "rrrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrr rrrrrrrrrrrrrr rrrrrrrrrr",
        inCart : false,
        count : 1, 
    },
    {
        id : 8,
        img : "img/car2.jpg",
        title : "Car8",
        price : 34,
        company : "sssss",
        info : "dddddd dddddddddddddd ddddddddddd",
        inCart : false,
        count : 1, 
    },
    {
        id : 9,
        img : "img/car3.jpg",
        title : "Car9",
        price : 56,
        company : "xxxxxx ",
        info : "cccccccc ccccccccccccc cccccccccccc ccccccccccc ccccc",
        inCart : false,
        count : 1, 
    },

]


export const prodInDetails = [
    {
        id : 1,
        img : "img/car1.jpg",
        title : "Car1",
        price : 12,
        company : "eeeeeee",
        info : "rrrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrr rrrrrrrrrrrrrr rrrrrrrrrr",
        inCart : false,
        count : 1, 
    },
    {
        id : 2,
        img : "img/car2.jpg",
        title : "Car2",
        price : 34,
        company : "sssss",
        info : "dddddd dddddddddddddd ddddddddddd",
        inCart : false,
        count : 1, 
    },
    {
        id : 3,
        img : "img/car3.jpg",
        title : "Car3",
        price : 56,
        company : "xxxxxx ",
        info : "cccccccc ccccccccccccc cccccccccccc ccccccccccc ccccc",
        inCart : false,
        count : 1, 
    },
    {
        id : 4,
        img : "img/car1.jpg",
        title : "Car4",
        price : 12,
        company : "eeeeeee",
        info : "rrrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrr rrrrrrrrrrrrrr rrrrrrrrrr",
        inCart : false,
        count : 1, 
    },
    {
        id : 5,
        img : "img/car2.jpg",
        title : "Car5",
        price : 34,
        company : "sssss",
        info : "dddddd dddddddddddddd ddddddddddd",
        inCart : false,
        count : 1, 
    },
    {
        id : 6,
        img : "img/car3.jpg",
        title : "Car6",
        price : 56,
        company : "xxxxxx ",
        info : "cccccccc ccccccccccccc cccccccccccc ccccccccccc ccccc",
        inCart : false,
        count : 1, 
    },
    {
        id : 7,
        img : "img/car1.jpg",
        title : "Car7",
        price : 12,
        company : "eeeeeee",
        info : "rrrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrr rrrrrrrrrrrrrr rrrrrrrrrr",
        inCart : false,
        count : 1, 
    },
    {
        id : 8,
        img : "img/car2.jpg",
        title : "Car8",
        price : 34,
        company : "sssss",
        info : "dddddd dddddddddddddd ddddddddddd",
        inCart : false,
        count : 1, 
    },
    {
        id : 9,
        img : "img/car3.jpg",
        title : "Car9",
        price : 56,
        company : "xxxxxx ",
        info : "cccccccc ccccccccccccc cccccccccccc ccccccccccc ccccc",
        inCart : false,
        count : 1, 
    },

]